SDKVERSION = 5.0
include theos/makefiles/common.mk

BUNDLE_NAME = LSBatteryPreferences
LSBatteryPreferences_FILES = LSBatteryPreferences.mm
LSBatteryPreferences_INSTALL_PATH = /Library/PreferenceBundles
LSBatteryPreferences_PRIVATE_FRAMEWORKS = Preferences

include theos/makefiles/bundle.mk
